### ISSUE TITLE
强制删除运行中的下载任务，在重新订阅后无法开始并且“文件已下载”检测不准确

### ISSUE THREAD

**Issue by pein0saga** [wushuo894/ani-rss#108]
### 请勾选您确认过的前置条件

- [X] 我已经阅读了 [常见问题](https://docs.wushuo.top/faq.html) [使用文档](https://docs.wushuo.top/add-rss.html)

- [X] 我确定没有重复的issue或discussions

- [X] 我确定这是程序本身的问题而不是其他 (比如网络相关的报错)

- [X] 我确定这个问题在最新版本中没有被修复

### 运行环境

- [ ] Docker

- [ ] Linux

- [ ] macOS

- [ ] Windows

- [X] 群晖套件

### 程序版本

v1.1.207

### 问题描述

相关订阅 やり直し令嬢は竜帝陛下を攻略中 

最开始是没搞懂选择下载功能，自动开始了下载1-8集的任务，去QB里面强行停止删除。

```
24-12-06 16:27:52 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E06
2024-12-06 16:27:52 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E06
2024-12-06 16:28:05 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E07
2024-12-06 16:28:05 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E07
2024-12-06 16:29:08 ERROR ani.rss.util.TorrentUtil - やり直し令嬢は竜帝陛下を攻略中 (2024) S01E07 添加失败，疑似为坏种
2024-12-06 16:29:18 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E08
2024-12-06 16:29:18 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E08
2024-12-06 16:29:52 INFO ani.rss.util.TorrentUtil - 删除任务 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E08
2024-12-06 16:29:55 INFO ani.rss.util.TorrentUtil - 删除任务成功 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E08
```
截取6-8的日志

紧接着马上删除了控制台的订阅，再重新添加的时候发现5-8的文件是“已下载”状态，但实际上确认过这是错误的，导致这个任务无法正常开始。

### 日志

2024-12-06 16:26:32 INFO ani.rss.action.AniAction - 添加订阅 やり直し令嬢は竜帝陛下を攻略中 (2024) https://mikanime.tv/RSS/Bangumi?bangumiId=3444&subgroupid=1208 3c24c007-0246-443f-aab2-c4831d760d38
2024-12-06 16:26:36 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E01
2024-12-06 16:26:36 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E01
2024-12-06 16:26:51 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E02
2024-12-06 16:26:51 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E02
2024-12-06 16:27:06 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E03
2024-12-06 16:27:06 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E03
2024-12-06 16:27:20 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E04
2024-12-06 16:27:20 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E04
2024-12-06 16:27:35 INFO ani.rss.action.ClearCacheAction - 清理空文件夹 /var/packages/ani-rss/var/config/torrents/#/やり直し令嬢は竜帝陛下を攻略中 (2024)
2024-12-06 16:27:35 INFO ani.rss.action.ClearCacheAction - 清理空文件夹 /var/packages/ani-rss/var/config/torrents/#
2024-12-06 16:27:35 INFO ani.rss.action.AniAction - 删除订阅 やり直し令嬢は竜帝陛下を攻略中 (2024) https://mikanime.tv/RSS/Bangumi?bangumiId=3444&subgroupid=1208 3c24c007-0246-443f-aab2-c4831d760d38
2024-12-06 16:27:37 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E05
2024-12-06 16:27:37 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E05
2024-12-06 16:27:52 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E06
2024-12-06 16:27:52 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E06
2024-12-06 16:28:05 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E07
2024-12-06 16:28:05 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E07
2024-12-06 16:29:08 ERROR ani.rss.util.TorrentUtil - やり直し令嬢は竜帝陛下を攻略中 (2024) S01E07 添加失败，疑似为坏种
2024-12-06 16:29:18 INFO ani.rss.util.TorrentUtil - 添加下载 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E08
2024-12-06 16:29:18 INFO ani.rss.util.TorrentUtil - 下载种子 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E08
2024-12-06 16:29:52 INFO ani.rss.util.TorrentUtil - 删除任务 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E08
2024-12-06 16:29:55 INFO ani.rss.util.TorrentUtil - 删除任务成功 やり直し令嬢は竜帝陛下を攻略中 (2024) S01E08
2024-12-06 16:29:56 ERROR ani.rss.task.RenameTask - status: 404
java.lang.IllegalArgumentException: status: 404
	at cn.hutool.core.lang.Assert.lambda$isTrue$0(Assert.java:54)
	at cn.hutool.core.lang.Assert.isTrue(Assert.java:37)
	at cn.hutool.core.lang.Assert.isTrue(Assert.java:54)
	at ani.rss.download.qBittorrent.lambda$files$7(qBittorrent.java:250)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1078)
	at ani.rss.download.qBittorrent.files(qBittorrent.java:249)
	at ani.rss.download.qBittorrent.lambda$getTorrentsInfos$1(qBittorrent.java:101)
	at ani.rss.download.qBittorrent.rename(qBittorrent.java:283)
	at ani.rss.util.TorrentUtil.rename(TorrentUtil.java:905)
	at ani.rss.task.RenameTask.run(RenameTask.java:47)
2024-12-06 16:29:58 INFO ani.rss.action.AniAction - 删除 /volume2/SortNew/DL/2024-10/やり直し令嬢は竜帝陛下を攻略中 (2024)/S01
2024-12-06 16:29:58 INFO ani.rss.action.ClearCacheAction - 清理空文件夹 /volume2/SortNew/DL/2024-10/やり直し令嬢は竜帝陛下を攻略中 (2024)
2024-12-06 16:36:18 ERROR ani.rss.util.HttpRequestPlus - url: http://127.0.0.1:8085/api/v2/torrents/info, error: Read timed out
2024-12-06 16:36:18 ERROR ani.rss.util.TorrentUtil - Read timed out
cn.hutool.http.HttpException: Read timed out
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.getTorrentsInfos(qBittorrent.java:75)
	at ani.rss.util.TorrentUtil.getTorrentsInfos(TorrentUtil.java:650)
	at ani.rss.task.RenameTask.run(RenameTask.java:40)
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1709)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1610)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482)
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.getTorrentsInfos(qBittorrent.java:75)
	at ani.rss.util.TorrentUtil.getTorrentsInfos(TorrentUtil.java:650)
	at ani.rss.task.RenameTask.run(RenameTask.java:40)
2024-12-06 16:43:03 ERROR ani.rss.util.HttpRequestPlus - url: http://127.0.0.1:8085/api/v2/torrents/info, error: Read timed out
2024-12-06 16:43:03 ERROR ani.rss.util.TorrentUtil - Read timed out
cn.hutool.http.HttpException: Read timed out
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.getTorrentsInfos(qBittorrent.java:75)
	at ani.rss.util.TorrentUtil.getTorrentsInfos(TorrentUtil.java:650)
	at ani.rss.task.RenameTask.run(RenameTask.java:40)
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1709)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1610)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482)
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.getTorrentsInfos(qBittorrent.java:75)
	at ani.rss.util.TorrentUtil.getTorrentsInfos(TorrentUtil.java:650)
	at ani.rss.task.RenameTask.run(RenameTask.java:40)
2024-12-06 16:44:34 INFO ani.rss.action.AniAction - 添加订阅 やり直し令嬢は竜帝陛下を攻略中 (2024) https://mikanime.tv/RSS/Bangumi?bangumiId=3444&subgroupid=1208 3078d91e-5576-4773-b282-496d7311f8d1
2024-12-06 16:45:01 ERROR ani.rss.util.HttpRequestPlus - url: http://127.0.0.1:8085/api/v2/torrents/info, error: Read timed out
2024-12-06 16:45:01 ERROR ani.rss.util.TorrentUtil - Read timed out
cn.hutool.http.HttpException: Read timed out
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.getTorrentsInfos(qBittorrent.java:75)
	at ani.rss.util.TorrentUtil.getTorrentsInfos(TorrentUtil.java:650)
	at ani.rss.util.TorrentUtil.downloadAni(TorrentUtil.java:51)
	at ani.rss.task.RssTask.download(RssTask.java:63)
	at ani.rss.task.RssTask.run(RssTask.java:104)
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1709)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1610)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482)
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.getTorrentsInfos(qBittorrent.java:75)
	at ani.rss.util.TorrentUtil.getTorrentsInfos(TorrentUtil.java:650)
	at ani.rss.util.TorrentUtil.downloadAni(TorrentUtil.java:51)
	at ani.rss.task.RssTask.download(RssTask.java:63)
	at ani.rss.task.RssTask.run(RssTask.java:104)
2024-12-06 16:46:47 INFO ani.rss.action.ProxyAction - https://mikanani.me
2024-12-06 16:48:11 INFO ani.rss.action.AniAction - 修改订阅 青之箱 (2024) https://mikanime.tv/RSS/Bangumi?bangumiId=3443&subgroupid=611 b07397f9-f3f0-4ed7-99dd-ddaf916371af
2024-12-06 16:48:45 INFO ani.rss.action.AniAction - 修改订阅 アオのハコ (2024) https://mikanime.tv/RSS/Bangumi?bangumiId=3443&subgroupid=611 b07397f9-f3f0-4ed7-99dd-ddaf916371af
2024-12-06 16:48:47 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E06 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:48:48 ERROR ani.rss.download.qBittorrent - Error request, response status: 502
2024-12-06 16:48:48 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E10 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:48:49 ERROR ani.rss.download.qBittorrent - Error request, response status: 502
2024-12-06 16:48:49 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E08 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:48:55 ERROR ani.rss.util.HttpRequestPlus - url: http://127.0.0.1:8085/api/v2/torrents/setAutoManagement, error: Read timed out
2024-12-06 16:48:55 ERROR ani.rss.util.TorrentUtil - Read timed out
cn.hutool.http.HttpException: Read timed out
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.setSavePath(qBittorrent.java:372)
	at ani.rss.util.TorrentUtil.setSavePath(TorrentUtil.java:934)
	at ani.rss.action.AniAction.lambda$put$9(AniAction.java:179)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1709)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1610)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482)
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.setSavePath(qBittorrent.java:372)
	at ani.rss.util.TorrentUtil.setSavePath(TorrentUtil.java:934)
	at ani.rss.action.AniAction.lambda$put$9(AniAction.java:179)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-12-06 16:48:55 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E09 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:48:56 ERROR ani.rss.download.qBittorrent - Error request, response status: 502
2024-12-06 16:48:56 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E02 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:48:56 ERROR ani.rss.download.qBittorrent - Error request, response status: 502
2024-12-06 16:48:56 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E03 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:48:59 ERROR ani.rss.download.qBittorrent - Error request, response status: 502
2024-12-06 16:48:59 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E04 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:48:59 ERROR ani.rss.download.qBittorrent - Error request, response status: 502
2024-12-06 16:48:59 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E07 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:00 ERROR ani.rss.download.qBittorrent - Error request, response status: 502
2024-12-06 16:49:00 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E05 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:01 ERROR ani.rss.download.qBittorrent - Error request, response status: 502
2024-12-06 16:49:01 INFO ani.rss.util.TorrentUtil - 修改保存位置 青之箱 (2024) S01E01 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:02 ERROR ani.rss.download.qBittorrent - Error request, response status: 502
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E05.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E01.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E09.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E06.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E04.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E08.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E07.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E03.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E02.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.AniAction - 移动文件 /volume2/SortNew/DL/2024-10/青之箱 (2024)/S01/青之箱 (2024) S01E10.mp4 ==> /volume2/SortNew/DL/2024-10/アオのハコ (2024)/S01
2024-12-06 16:49:05 INFO ani.rss.action.ClearCacheAction - 清理空文件夹 /volume2/SortNew/DL/2024-10/青之箱 (2024)
2024-12-06 16:50:03 INFO ani.rss.action.AniAction - 修改订阅 やり直し令嬢は竜帝陛下を攻略中 (2024) https://mikanime.tv/RSS/Bangumi?bangumiId=3444&subgroupid=1208 3078d91e-5576-4773-b282-496d7311f8d1
2024-12-06 16:55:12 INFO ani.rss.action.AniAction - 修改订阅 やり直し令嬢は竜帝陛下を攻略中 (2024) https://mikanime.tv/RSS/Bangumi?bangumiId=3444&subgroupid=1208 3078d91e-5576-4773-b282-496d7311f8d1
2024-12-06 16:55:26 INFO ani.rss.action.AniAction - 修改订阅 やり直し令嬢は竜帝陛下を攻略中 (2024) https://mikanime.tv/RSS/Bangumi?bangumiId=3444&subgroupid=1208 3078d91e-5576-4773-b282-496d7311f8d1
2024-12-06 16:55:39 INFO ani.rss.action.AniAction - 修改订阅 やり直し令嬢は竜帝陛下を攻略中 (2024) https://mikanime.tv/RSS/Bangumi?bangumiId=3444&subgroupid=1208 3078d91e-5576-4773-b282-496d7311f8d1

**Comment by wushuo894** [comment]
> 备注下，QB也是群晖端的套件，都没用DOCKER

https://docs.wushuo.top/faq.html#%E5%88%A0%E9%99%A4%E4%BA%86%E8%A7%86%E9%A2%91-%E5%9C%A8%E9%A2%84%E8%A7%88%E4%B8%AD%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%9C%A8

**Comment by wushuo894** [comment]
> > > 备注下，QB也是群晖端的套件，都没用DOCKER
> > 
> > 
> > https://docs.wushuo.top/faq.html#%E5%88%A0%E9%99%A4%E4%BA%86%E8%A7%86%E9%A2%91-%E5%9C%A8%E9%A2%84%E8%A7%88%E4%B8%AD%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%9C%A8
> 
> 谢谢，但是我认为这个是应该作为bug被修复的（比如加个判断提示用户有种子缓存而没有对应下完的文件，或者加个刷新图标清空种子缓存，而不是手动删除种子[现在界面上看不出某个种子是否被缓存过]），
> 
> 除非因为技术规划问题要延期修复所以作为临时解决方案才暂且放到FAQ里面。

存放种子并根据种子判断是为了对比种子的hash，并可以洗版。

**Comment by wushuo894** [comment]
> > > > > 备注下，QB也是群晖端的套件，都没用DOCKER
> 
> > > > 
> 
> > > > 
> 
> > > > https://docs.wushuo.top/faq.html#%E5%88%A0%E9%99%A4%E4%BA%86%E8%A7%86%E9%A2%91-%E5%9C%A8%E9%A2%84%E8%A7%88%E4%B8%AD%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%9C%A8
> 
> > > 
> 
> > > 
> 
> > > 谢谢，但是我认为这个是应该作为bug被修复的（比如加个判断提示用户有种子缓存而没有对应下完的文件，或者加个刷新图标清空种子缓存，而不是手动删除种子[现在界面上看不出某个种子是否被缓存过]），
> 
> > > 除非因为技术规划问题要延期修复所以作为临时解决方案才暂且放到FAQ里面。
> 
> > 
> 
> > 存放种子并根据种子判断是为了对比种子的hash，并可以洗版。
> 
> 
> 
> 好的。希望能加个注释，“洗版”是指用不同的字幕组的视频和字幕之间相互替代吗？

对
