### ISSUE TITLE
ERROR ani.rss.Main - Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive

### ISSUE THREAD

**Issue by LperZ** [wushuo894/ani-rss#25]
昨晚遭遇停电电脑断电了重启后程序就打不开了，报错如下：
2024-09-14 10:35:23.572 [main] INFO  ani.rss.util.TorrentUtil - 下载工具 qBittorrent 
2024-09-14 10:35:23.577 [main] ERROR ani.rss.Main - Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive; at path $
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive; at path $
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1010)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at ani.rss.util.AniUtil.load(AniUtil.java:65)
	at ani.rss.Main.main(Main.java:12)

**Comment by wushuo894** [comment]
你看一下程序同级目录下的config/ani.json，应该是保存时出现了终止，导致的损坏。你也可以删除这个文件，但会导致你的订阅丢失
