### ISSUE TITLE
rss解析失败

### ISSUE THREAD

**Issue by 111234567890** [wushuo894/ani-rss#39]
![image](https://github.com/user-attachments/assets/61992452-2b4a-4426-9489-2b01b3897976)
这是报错信息：
2024-10-10 02:21:47 ERROR ani.rss.util.AniUtil - Read timed out
cn.hutool.http.HttpException: Read timed out
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:224)
	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:217)
	at ani.rss.util.AniUtil.getAni(AniUtil.java:183)
	at ani.rss.action.RssAction.doAction(RssAction.java:38)
	at ani.rss.util.ServerUtil$1.doAction(ServerUtil.java:95)
	at cn.hutool.http.server.handler.ActionHandler.handle(ActionHandler.java:44)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at ani.rss.util.ServerUtil.lambda$create$0(ServerUtil.java:66)
	at cn.hutool.http.server.SimpleServer$1.doFilter(SimpleServer.java:130)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-10-10 02:21:47 ERROR ani.rss.action.RssAction - 获取bgm信息失败
java.lang.RuntimeException: 获取bgm信息失败
	at ani.rss.util.AniUtil.getAni(AniUtil.java:205)
	at ani.rss.action.RssAction.doAction(RssAction.java:38)
	at ani.rss.util.ServerUtil$1.doAction(ServerUtil.java:95)
	at cn.hutool.http.server.handler.ActionHandler.handle(ActionHandler.java:44)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at ani.rss.util.ServerUtil.lambda$create$0(ServerUtil.java:66)
	at cn.hutool.http.server.SimpleServer$1.doFilter(SimpleServer.java:130)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	
	在代理设置里测试连通性正常
	
![image](https://github.com/user-attachments/assets/743f8045-15ce-4caf-bffb-9c17e9895fb5)
之前成功下载到了一个番剧，后边再添加突然就不行了
![PANBXL{V%B31YJM))`6Q9NU](https://github.com/user-attachments/assets/ea3e8a5a-f734-46a9-9d6a-9a07e0a0a5c9)

**Comment by wushuo894** [comment]
> ![image](https://github.com/user-attachments/assets/61992452-2b4a-4426-9489-2b01b3897976)
> 
> 这是报错信息：
> 
> 2024-10-10 02:21:47 ERROR ani.rss.util.AniUtil - Read timed out
> 
> cn.hutool.http.HttpException: Read timed out
> 
> 	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283)
> 
> 	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
> 
> 	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
> 
> 	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
> 
> 	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
> 
> 	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:224)
> 
> 	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:217)
> 
> 	at ani.rss.util.AniUtil.getAni(AniUtil.java:183)
> 
> 	at ani.rss.action.RssAction.doAction(RssAction.java:38)
> 
> 	at ani.rss.util.ServerUtil$1.doAction(ServerUtil.java:95)
> 
> 	at cn.hutool.http.server.handler.ActionHandler.handle(ActionHandler.java:44)
> 
> 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
> 
> 	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
> 
> 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
> 
> 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
> 
> 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
> 
> 	at ani.rss.util.ServerUtil.lambda$create$0(ServerUtil.java:66)
> 
> 	at cn.hutool.http.server.SimpleServer$1.doFilter(SimpleServer.java:130)
> 
> 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
> 
> 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 
> 	at java.base/java.lang.Thread.run(Unknown Source)
> 
> 2024-10-10 02:21:47 ERROR ani.rss.action.RssAction - 获取bgm信息失败
> 
> java.lang.RuntimeException: 获取bgm信息失败
> 
> 	at ani.rss.util.AniUtil.getAni(AniUtil.java:205)
> 
> 	at ani.rss.action.RssAction.doAction(RssAction.java:38)
> 
> 	at ani.rss.util.ServerUtil$1.doAction(ServerUtil.java:95)
> 
> 	at cn.hutool.http.server.handler.ActionHandler.handle(ActionHandler.java:44)
> 
> 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
> 
> 	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
> 
> 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
> 
> 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
> 
> 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
> 
> 	at ani.rss.util.ServerUtil.lambda$create$0(ServerUtil.java:66)
> 
> 	at cn.hutool.http.server.SimpleServer$1.doFilter(SimpleServer.java:130)
> 
> 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
> 
> 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 
> 	at java.base/java.lang.Thread.run(Unknown Source)
> 
> 	
> 
> 	在代理设置里测试连通性正常
> 
> 	
> 
> ![image](https://github.com/user-attachments/assets/743f8045-15ce-4caf-bffb-9c17e9895fb5)
> 
> 之前成功下载到了一个番剧，后边再添加突然就不行了
> 
> ![PANBXL{V%B31YJM))`6Q9NU](https://github.com/user-attachments/assets/ea3e8a5a-f734-46a9-9d6a-9a07e0a0a5c9)
> 
> 
> 
> 	

time out 你的网络问题，完善一下你的科学上网
