### ISSUE TITLE
[Bug反馈]  arm64平台访问https://mikanime.tv 超时（未使用代理）

### ISSUE THREAD

**Issue by LSP0123** [wushuo894/ani-rss#50]
```
2024-10-13 20:05:01 ERROR ani.rss.action.MikanAction - /api/mikan SocketTimeoutException: Connect timed out
2024-10-13 20:05:01 ERROR ani.rss.action.MikanAction - SocketTimeoutException: Connect timed out
cn.hutool.core.io.IORuntimeException: SocketTimeoutException: Connect timed out
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1350)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1188)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.util.MikanUtil.list(MikanUtil.java:50)
	at ani.rss.action.MikanAction.doAction(MikanAction.java:19)
	at ani.rss.util.ServerUtil$1.doAction(ServerUtil.java:95)
	at cn.hutool.http.server.handler.ActionHandler.handle(ActionHandler.java:44)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at ani.rss.util.ServerUtil.lambda$create$0(ServerUtil.java:66)
	at cn.hutool.http.server.SimpleServer$1.doFilter(SimpleServer.java:130)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-10-13 20:06:05 ERROR ani.rss.action.MikanAction - /api/mikan SocketTimeoutException: Connect timed out
2024-10-13 20:06:05 ERROR ani.rss.action.MikanAction - SocketTimeoutException: Connect timed out
cn.hutool.core.io.IORuntimeException: SocketTimeoutException: Connect timed out
	at cn.hutool.http.HttpRequest.send(HttpRequest.java:1350)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1188)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.util.MikanUtil.list(MikanUtil.java:50)
	at ani.rss.action.MikanAction.doAction(MikanAction.java:19)
	at ani.rss.util.ServerUtil$1.doAction(ServerUtil.java:95)
	at cn.hutool.http.server.handler.ActionHandler.handle(ActionHandler.java:44)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at ani.rss.util.ServerUtil.lambda$create$0(ServerUtil.java:66)
	at cn.hutool.http.server.SimpleServer$1.doFilter(SimpleServer.java:130)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

本地x86设备通过浏览器访问及arm平台使用curl获取https://mikanime.tv正常（无任何代理情况下）

![image](https://github.com/user-attachments/assets/be2bcbfb-ce2e-406e-aac4-bc96b112cbe0)

**Comment by wushuo894** [comment]
你在 容器内命令行 测试一下能否访问mikan

**Comment by wushuo894** [comment]
我做的超时限制为6秒

**Comment by wushuo894** [comment]
> 没使用容器，直接host跑的，mikan是可以访问的 ![image](https://private-user-images.githubusercontent.com/31061624/376033543-7e047f22-17ba-4921-94a1-03d14e1f29b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjIzMzEsIm5iZiI6MTcyODgyMjAzMSwicGF0aCI6Ii8zMTA2MTYyNC8zNzYwMzM1NDMtN2UwNDdmMjItMTdiYS00OTIxLTk0YTEtMDNkMTRlMWYyOWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEyMjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNDJmNjk2ZGI0ODU5ZTc1YjNiNzE3ZjU4NWM4M2M0MDZkYWU1NjBkN2E5MjNkMDQ2YWNmOTRmOWYyYTY4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0-2qAbBT8DPuTWJQrAcpcpSArSlJnAWX_2B2QhKxV-g)

在设置代理页面测试一下

**Comment by wushuo894** [comment]
> 没使用容器，直接host跑的，mikan是可以访问的 ![image](https://private-user-images.githubusercontent.com/31061624/376033543-7e047f22-17ba-4921-94a1-03d14e1f29b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjMwODAsIm5iZiI6MTcyODgyMjc4MCwicGF0aCI6Ii8zMTA2MTYyNC8zNzYwMzM1NDMtN2UwNDdmMjItMTdiYS00OTIxLTk0YTEtMDNkMTRlMWYyOWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEyMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NTYwODVmMzJhMTVhM2MzNzMzN2YxODFhNTQ2OWRkNjcxNWYzOWVkYTYyMTk0MTlkNTVkZDMzZTZlMDgyZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lyrTymAbTIFkDmrHaMJlGfYt5h7fyiBLnGSYK2vuxNs)
> 
> ```
> sudo systemctl cat Ani-RSS.service 
> # /etc/systemd/system/Ani-RSS.service
> [Unit]
> Description=Start Ani-RSS jar file
> After=multi-user.target
> 
> [Service]
> ExecStart=/usr/bin/java -jar -Xmx512M  /opt/Ani-RSS/ani-rss-jar-with-dependencies.jar --port 7789
> Type=simple
> WorkingDirectory=/opt/Ani-RSS
> User=qbtuser
> 
> [Install]
> WantedBy=multi-user.target
> ```

建议使用这个启动脚本 https://github.com/wushuo894/ani-rss/blob/master/docker/run.sh

可以让更新后自启动
