### ISSUE TITLE
启动一段时间后无法打开ui

### ISSUE THREAD

**Issue by feather-of-sheep2000** [wushuo894/ani-rss#66]
win10系统，使用最新的release文件，v1.1.160版exe，qb用的是qBittorrent Enhanced Edition v4.4.3.12，配置完qb的web ui之后，确认可以完成下载。在放置几个小时后，无法打开ani-rss的ui界面（如下图一），重新启动ani-rss后才可以打开ui，但是测试qb连接提示无法登录，日志中也报错无法登录qb，此时必须随便修改一下qb端口后才能再次登录成功。应该不是端口被其他程序占用，因为改过好几个端口，依然是同样的问题
图一 无法打开ui界面
![image](https://github.com/user-attachments/assets/35905edf-3432-4242-8ff2-3ea20da0b997)
 图二 qb配置
![image](https://github.com/user-attachments/assets/c12812b5-2959-4f0f-a8e6-e587e9350d4c)

以下是重新启动之后的日志，因为之后基本都是重复的报错，所以只复制了前面这一部分：
2024-10-27 23:52:48 INFO ani.rss.util.TorrentUtil - 下载工具 qBittorrent
2024-10-27 23:52:48 INFO ani.rss.task.RssTask - rss-task-thread 当前设置间隔为 15 分钟
2024-10-27 23:52:48 INFO ani.rss.task.BgmTask - bgm-task-thread 任务正在运行
2024-10-27 23:52:48 INFO ani.rss.task.RenameTask - rename-task-thread 当前设置间隔为 1.0 分钟
2024-10-27 23:52:48 INFO ani.rss.Main - version 1.1.160
2024-10-27 23:52:49 INFO ani.rss.util.MenuUtil - 启动系统托盘已启动
2024-10-27 23:52:49 ERROR ani.rss.download.qBittorrent - Connection reset
cn.hutool.http.HttpException: Connection reset
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.login(qBittorrent.java:56)
	at ani.rss.util.TorrentUtil.login(TorrentUtil.java:555)
	at ani.rss.task.RssTask.download(RssTask.java:32)
	at ani.rss.task.RssTask.run(RssTask.java:104)
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:827)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:786)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1705)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482)
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.login(qBittorrent.java:56)
	at ani.rss.util.TorrentUtil.login(TorrentUtil.java:555)
	at ani.rss.task.RssTask.download(RssTask.java:32)
	at ani.rss.task.RssTask.run(RssTask.java:104)
2024-10-27 23:52:49 ERROR ani.rss.download.qBittorrent - 登录 qBittorrent 失败 Connection reset
2024-10-27 23:52:50 ERROR ani.rss.download.qBittorrent - Connection reset
cn.hutool.http.HttpException: Connection reset
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.login(qBittorrent.java:56)
	at ani.rss.util.TorrentUtil.login(TorrentUtil.java:555)
	at ani.rss.task.RenameTask.run(RenameTask.java:35)
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:827)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:786)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1705)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482)
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.download.qBittorrent.login(qBittorrent.java:56)
	at ani.rss.util.TorrentUtil.login(TorrentUtil.java:555)
	at ani.rss.task.RenameTask.run(RenameTask.java:35)
2024-10-27 23:52:50 ERROR ani.rss.download.qBittorrent - 登录 qBittorrent 失败 Connection reset
2024-10-27 23:53:00 ERROR ani.rss.task.BgmTask - Read timed out
cn.hutool.http.HttpException: Read timed out
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:295)
	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:236)
	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:232)
	at ani.rss.task.BgmTask.run(BgmTask.java:46)
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:827)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1705)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482)
	at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279)
	at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051)
	at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42)
	at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077)
	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:295)
	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:236)
	at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:232)
	at ani.rss.task.BgmTask.run(BgmTask.java:46)

**Comment by wushuo894** [comment]
> win10系统，使用最新的release文件，v1.1.160版exe，qb用的是qBittorrent Enhanced Edition v4.4.3.12，配置完qb的web ui之后，确认可以完成下载。在放置几个小时后，无法打开ani-rss的ui界面（如下图一），重新启动ani-rss后才可以打开ui，但是测试qb连接提示无法登录，日志中也报错无法登录qb，此时必须随便修改一下qb端口后才能再次登录成功。应该不是端口被其他程序占用，因为改过好几个端口，依然是同样的问题 图一 无法打开ui界面 ![image](https://private-user-images.githubusercontent.com/122247608/380513546-35905edf-3432-4242-8ff2-3ea20da0b997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNDc4NzIsIm5iZiI6MTczMDA0NzU3MiwicGF0aCI6Ii8xMjIyNDc2MDgvMzgwNTEzNTQ2LTM1OTA1ZWRmLTM0MzItNDI0Mi04ZmYyLTNlYTIwZGEwYjk5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxNjQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODNlYzdhNDQ3YmNmZTFlYmVmMTFiODY0Mjk0MDgwOWIwNGIwMjdlNzZmZWMxMzA4ZGVjZjAwMzNjYmE0Y2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.33qIg3xbm5abU-wNhM2AOqmjvJpLkkmu56KLePVl4JE) 图二 qb配置 ![image](https://private-user-images.githubusercontent.com/122247608/380514495-c12812b5-2959-4f0f-a8e6-e587e9350d4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNDc4NzIsIm5iZiI6MTczMDA0NzU3MiwicGF0aCI6Ii8xMjIyNDc2MDgvMzgwNTE0NDk1LWMxMjgxMmI1LTI5NTktNGYwZi1hOGU2LWU1ODdlOTM1MGQ0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxNjQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDU2MzhmZGFmYTllMWYwZDE5NjI2YThhOGQxMjkxOTA2MDY2NTU4NDhiMGU3NDE0ZGFkN2IyODQxZDdkZmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.deKa_YYn83DEYZeChfoJCLlsBDsH7xEGF8lF-3FwndU)
> 
> 以下是重新启动之后的日志，因为之后基本都是重复的报错，所以只复制了前面这一部分： 2024-10-27 23:52:48 INFO ani.rss.util.TorrentUtil - 下载工具 qBittorrent 2024-10-27 23:52:48 INFO ani.rss.task.RssTask - rss-task-thread 当前设置间隔为 15 分钟 2024-10-27 23:52:48 INFO ani.rss.task.BgmTask - bgm-task-thread 任务正在运行 2024-10-27 23:52:48 INFO ani.rss.task.RenameTask - rename-task-thread 当前设置间隔为 1.0 分钟 2024-10-27 23:52:48 INFO ani.rss.Main - version 1.1.160 2024-10-27 23:52:49 INFO ani.rss.util.MenuUtil - 启动系统托盘已启动 2024-10-27 23:52:49 ERROR ani.rss.download.qBittorrent - Connection reset cn.hutool.http.HttpException: Connection reset at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283) at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191) at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051) at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42) at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077) at ani.rss.download.qBittorrent.login(qBittorrent.java:56) at ani.rss.util.TorrentUtil.login(TorrentUtil.java:555) at ani.rss.task.RssTask.download(RssTask.java:32) at ani.rss.task.RssTask.run(RssTask.java:104) java.net.SocketException: Connection reset at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318) at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099) at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291) at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347) at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420) at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399) at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:827) at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759) at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:786) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1705) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614) at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531) at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482) at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279) at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191) at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051) at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42) at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077) at ani.rss.download.qBittorrent.login(qBittorrent.java:56) at ani.rss.util.TorrentUtil.login(TorrentUtil.java:555) at ani.rss.task.RssTask.download(RssTask.java:32) at ani.rss.task.RssTask.run(RssTask.java:104) 2024-10-27 23:52:49 ERROR ani.rss.download.qBittorrent - 登录 qBittorrent 失败 Connection reset 2024-10-27 23:52:50 ERROR ani.rss.download.qBittorrent - Connection reset cn.hutool.http.HttpException: Connection reset at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283) at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191) at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051) at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42) at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077) at ani.rss.download.qBittorrent.login(qBittorrent.java:56) at ani.rss.util.TorrentUtil.login(TorrentUtil.java:555) at ani.rss.task.RenameTask.run(RenameTask.java:35) java.net.SocketException: Connection reset at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318) at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099) at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291) at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347) at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420) at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399) at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:827) at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759) at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:786) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1705) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614) at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531) at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482) at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279) at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191) at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051) at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42) at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077) at ani.rss.download.qBittorrent.login(qBittorrent.java:56) at ani.rss.util.TorrentUtil.login(TorrentUtil.java:555) at ani.rss.task.RenameTask.run(RenameTask.java:35) 2024-10-27 23:52:50 ERROR ani.rss.download.qBittorrent - 登录 qBittorrent 失败 Connection reset 2024-10-27 23:53:00 ERROR ani.rss.task.BgmTask - Read timed out cn.hutool.http.HttpException: Read timed out at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1283) at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191) at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051) at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42) at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077) at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:295) at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:236) at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:232) at ani.rss.task.BgmTask.run(BgmTask.java:46) java.net.SocketTimeoutException: Read timed out at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278) at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304) at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099) at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489) at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461) at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066) at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291) at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347) at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420) at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399) at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:827) at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1705) at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614) at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531) at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307) at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:482) at cn.hutool.http.HttpRequest.sendRedirectIfPossible(HttpRequest.java:1279) at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1191) at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051) at ani.rss.util.HttpRequestPlus.execute(HttpRequestPlus.java:42) at cn.hutool.http.HttpRequest.thenFunction(HttpRequest.java:1077) at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:295) at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:236) at ani.rss.util.BgmUtil.getBgmInfo(BgmUtil.java:232) at ani.rss.task.BgmTask.run(BgmTask.java:46)

你的windows开启休眠或者网卡休眠了吗？因为不只是qb会报错，bgm也连接超时。我怀疑在休眠时程序失去了ip绑定故无法访问

**Comment by wushuo894** [comment]
你也可以在休眠后自己访问一下qb的网址看看能否访问

**Comment by feather-of-sheep2000** [comment]
> 你也可以在休眠后自己访问一下qb的网址看看能否访问

试了一下休眠了十分钟，重新启动后qb的webui和ani-rss的ui访问都没有问题。之前出问题的时候的确有一次是休眠几个小时后不能打开，但是另一次中间电脑并没有休眠，只是单纯过了几个小时

**Comment by wushuo894** [comment]
> > 你也可以在休眠后自己访问一下qb的网址看看能否访问
> 
> 试了一下休眠了十分钟，重新启动后qb的webui和ani-rss的ui访问都没有问题。之前出问题的时候的确有一次是休眠几个小时后不能打开，但是另一次中间电脑并没有休眠，只是单纯过了几个小时

下次出现你记得测试一下qb和ass的webui能否访问如果同时不能访问大概率是系统或系统设置问题

**Comment by feather-of-sheep2000** [comment]
好的，我之后再测试一下

**Comment by wushuo894** [comment]
> 好的，我之后再测试一下

是否排查出来了

**Comment by feather-of-sheep2000** [comment]
> > 好的，我之后再测试一下
> 
> 是否排查出来了

目前还没能复现，等我周末电脑时间开长一些试试
